UMAprotocol/website

- docs/about.html
- docs/index.html
- src/partials/footer-smaller.html
- src/partials/footer.html
> Update year in copyright from 2019 to 2020

- docs/about.html
- docs/index.html
- src/partials/header.html
> Add discord header

- src/assets/scss/components/_mobile-nav.scss
Add width so the button is easily accessible.
> Burger button width fix.

- src/projects.html
1. Added Jarvis Etherscan link.
2. Updated Perlin Etherscan link.
3. Fixed div and tab bug that caused Zelda Cash card to be present regardless of filter sort.
> Updated Etherscan links and fixed Zelda filter bug.

- src/projects.html
Reverts UMAprotocol/website#47
> Revert "Updated Etherscan links and fixed Zelda filter bug."

- src/index.html
Reverts UMAprotocol/website#61
> Revert "updated metrics"

- docs/uma.tokenlist.json
- src/uma.tokenlist.json
Adding the UMA 35 call to the Token List
> Updating the Token List to add the UMA 35 call

- docs/assets/images/sprite.symbol.html
- docs/index.html
- src/index.html
> fix: remove tvm column

- docs/assets/images/sprite.symbol.html
- docs/faq.html
- src/faq.html
Signed-off-by: Gamaranto <francesco@umaproject.org>
> fix(website):replace broken link

- docs/assets/images/sprite.symbol.html
- docs/projects.html
- src/projects.html
This PR fixes the broken select filter on the projects page. It basically consists of two steps:
1. Fixing the broken HTML, matching closing tags etc...
2. Rework the HTML to make filtering work
I've also formatted the whole `projects.html` as it makes it much more readable and should prevent unnecessary nesting in the future
> Fix filtering

- src/call-put.html
- src/kpi-options.html
- src/lsp.html
- src/optimistic-oracle.html
> copy updated.

- docs/assets/images/sprite.symbol.html
- docs/call-put.html
- docs/kpi-options.html
- docs/lsp.html
- docs/optimistic-oracle.html
Signed-off-by: Matt Rice <matthewcrice32@gmail.com>
> Run build for previous commit

- docs/assets/images/sprite.symbol.html
- docs/call-put.html
- docs/faq.html
- docs/index.html
- docs/kpi-options.html
- docs/lsp.html
- docs/optimistic-oracle.html
- docs/projects.html
- docs/range-tokens.html
- package-lock.json
- src/partials/header.html
**Motivation**
This PR adds a link to projects.umaproject.org 
MERGE AFTER UMAVERSE IS LIVE
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to test.
Signed-off-by: Gamaranto <francesco@umaproject.org>
> feat(website): add umaverse link

- docs/assets/images/sprite.symbol.html
- docs/range-tokens.html
- src/range-tokens.html
Updated range token button url.
> fix: updated range token button url

- docs/assets/images/sprite.symbol.html
- docs/index.html
- src/index.html
Signed-off-by: Gamaranto <francesco@umaproject.org>
> fix(website): add link

- src/assets/scss/components/_products.scss
Adjusted grid line to be more aligned.
> feat: Kpi final touchup

- src/index.html
Reverts UMAprotocol/website#109
> Revert "updated link"

- src/kpi-options.html
- src/optimistic-oracle.html
- src/range-tokens.html
- src/success-tokens.html
Updated links to reflect changes in the Docs website.
Signed-off-by: Alex Gaines <againes@umaproject.org>
> Update Product Pages Buttons

- src/optimistic-oracle.html
> updated links

- src/assets/js/modules/fetch-tvl.js
Signed-off-by: Alex Gaines <againes@umaproject.org>
> Update tvl to use defillama

- src/faq.html
- src/index.html
- src/optimistic-oracle.html
- src/partials/footer.html
- src/partials/header.html
- src/projects.html
- src/success-tokens.html
Added rel="noreferrer" to anchor tags.
> fix: Added noreferrer to all anchor tags with _blank

- src/partials/header.html
> fix: removed rewards tab

- src/kpi-options.html
- src/optimistic-oracle.html
- src/success-tokens.html
> fix: fixed text

- src/assets/js/modules/fetch-tvl.js
Signed-off-by: Alex Gaines <againes@umaproject.org>
This PR updates the TVL endpoint to use the updated Defillama oracle endpoint instead of TVL which is missing UMA integrations.
> Update TVL endpoint

- components/Faq/components.tsx
- components/Faq/index.tsx
- components/Footer/index.tsx
- components/GlobalStyles/index.tsx
- components/Header/components.tsx
- components/HomePage/features.ts
- components/HomePage/index.tsx
- pages/faq.tsx
Signed-off-by: amateima <amatei@umaproject.org>
Add `/faq` page
> feat: add FAQ page

- components/Footer/components.tsx
- components/Footer/index.tsx
- components/HomePage/features.ts
- components/HomePage/index.tsx
- components/HomePage/oo.ts
- components/ProductsPage/index.tsx
Signed-off-by: amateima <amatei@umaproject.org>
Just a bunch of texts updates
> fix: update texts

- components/Footer/index.tsx
Signed-off-by: amateima <amatei@umaproject.org>
> fix: fix FAQs footer href

- components/HomePage/components.tsx
Signed-off-by: amateima <amatei@umaproject.org
>
> fix: set oo boxes same height

- vercel.json
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
> Fix: Add html url

- vercel.json
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
> Fix OO redirect

- components/Header/index.tsx
Story details: https://app.shortcut.com/uma-project/story/5511
> feat: add verification to uma website for job board

- pages/products/call-put.tsx
- pages/products/range-tokens.tsx
Signed-off-by: Alex Gaines <againes@umaproject.org>
> fix: broken product urls
